// AI-assisted (Claude Code): this test file was generated by AI.

package runner

import (
	"encoding/csv"
	"math"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/google/go-cmp/cmp"
	"github.com/hirdrwit/oncorp/internal/config"
	icsv "github.com/hirdrwit/oncorp/internal/csv"
)

// day returns midnight UTC on the given date.
func day(year int, month time.Month, d int) time.Time {
	return time.Date(year, month, d, 0, 0, 0, 0, time.UTC)
}

// valid returns a row that has a value.
func valid(date time.Time, value float64) icsv.Row {
	return icsv.Row{Date: date, Value: value, Valid: true}
}

// blank returns a row that has no value, for example a market holiday.
func blank(date time.Time) icsv.Row {
	return icsv.Row{Date: date}
}

// dailyRows returns one valid row for each day from 1 January 2024. The
// row on day n (counted from 0) gets values[n].
func dailyRows(values ...float64) []icsv.Row {
	rows := make([]icsv.Row, 0, len(values))
	for n, v := range values {
		rows = append(rows, valid(day(2024, 1, 1+n), v))
	}
	return rows
}

// TestCalendarBack makes sure that the lookback from calendarBack finds the
// correct earlier row for rows[i]. A lookback is a function that finds the
// row to compare with. If wantOK is false, no row must be found and the
// index must be -1.
func TestCalendarBack(t *testing.T) {
	tests := []struct {
		name                string
		years, months, days int
		rows                []icsv.Row
		i                   int
		wantIndex           int
		wantOK              bool
	}{
		{
			name:      "previous day",
			days:      1,
			rows:      []icsv.Row{valid(day(2024, 1, 1), 10), valid(day(2024, 1, 2), 11)},
			i:         1,
			wantIndex: 0,
			wantOK:    true,
		},
		{
			name:      "first row has no earlier row",
			days:      1,
			rows:      []icsv.Row{valid(day(2024, 1, 1), 10)},
			i:         0,
			wantIndex: -1,
		},
		{
			name: "Monday goes back to Friday over the weekend",
			days: 1,
			rows: []icsv.Row{
				valid(day(2024, 1, 5), 10), // Friday
				valid(day(2024, 1, 8), 11), // Monday
			},
			i:         1,
			wantIndex: 0,
			wantOK:    true,
		},
		{
			name: "skips a row that is not valid",
			days: 1,
			rows: []icsv.Row{
				valid(day(2024, 1, 1), 10),
				blank(day(2024, 1, 2)),
				valid(day(2024, 1, 3), 12),
			},
			i:         2,
			wantIndex: 0,
			wantOK:    true,
		},
		{
			name: "only rows that are not valid",
			days: 1,
			rows: []icsv.Row{
				blank(day(2024, 1, 1)),
				blank(day(2024, 1, 2)),
				valid(day(2024, 1, 3), 12),
			},
			i:         2,
			wantIndex: -1,
		},
		{
			name: "earlier row is exactly maxGapDays before the target",
			days: 1,
			rows: []icsv.Row{
				valid(day(2024, 1, 1), 10),
				valid(day(2024, 1, 6), 11),
			},
			i:         1,
			wantIndex: 0,
			wantOK:    true,
		},
		{
			name: "earlier row is more than maxGapDays before the target",
			days: 1,
			rows: []icsv.Row{
				valid(day(2024, 1, 1), 10),
				valid(day(2024, 1, 7), 11),
			},
			i:         1,
			wantIndex: -1,
		},
		{
			name:      "one week back skips the rows after the target",
			days:      7,
			rows:      dailyRows(1, 2, 3, 4, 5, 6, 7, 8),
			i:         7,
			wantIndex: 0,
			wantOK:    true,
		},
		{
			name:      "one week back with no row in range",
			days:      7,
			rows:      dailyRows(1, 2, 3),
			i:         2,
			wantIndex: -1,
		},
		{
			name:   "one month back",
			months: 1,
			rows: []icsv.Row{
				valid(day(2024, 1, 15), 10),
				valid(day(2024, 2, 1), 11),
				valid(day(2024, 2, 15), 12),
			},
			i:         2,
			wantIndex: 0,
			wantOK:    true,
		},
		{
			name:  "one year back",
			years: 1,
			rows: []icsv.Row{
				valid(day(2023, 1, 13), 10), // Friday
				valid(day(2023, 6, 1), 11),
				valid(day(2024, 1, 15), 12),
			},
			i:         2,
			wantIndex: 0,
			wantOK:    true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			back := calendarBack(tt.years, tt.months, tt.days)
			gotIndex, gotOK := back(tt.rows, tt.i)
			if gotIndex != tt.wantIndex || gotOK != tt.wantOK {
				t.Errorf("calendarBack(%d, %d, %d)(rows, %d) = (%d, %t), want (%d, %t)",
					tt.years, tt.months, tt.days, tt.i, gotIndex, gotOK, tt.wantIndex, tt.wantOK)
			}
		})
	}
}

// TestGetDirection makes sure that getDirection returns "down" for a
// negative change and "up" for all other values.
func TestGetDirection(t *testing.T) {
	tests := []struct {
		v    float64
		want string
	}{
		{v: -25, want: "down"},
		{v: -0.0001, want: "down"},
		{v: 0, want: "up"},
		{v: 0.0001, want: "up"},
		{v: 25, want: "up"},
		{v: math.NaN(), want: "up"},
	}

	for _, tt := range tests {
		if got := getDirection(tt.v); got != tt.want {
			t.Errorf("getDirection(%v) = %q, want %q", tt.v, got, tt.want)
		}
	}
}

// TestRunChecker runs the day-over-day comparison on test data. Each case
// gives the files, the configuration for the check, and the results that
// runChecker must return. The values give exact float results, so the test
// can compare them with ==.
func TestRunChecker(t *testing.T) {
	tests := []struct {
		name  string
		files []*icsv.File
		cfg   config.Check
		want  []icsv.Result
	}{
		{
			name:  "no files",
			files: nil,
			cfg:   config.Check{ThresholdPct: 5},
			want:  nil,
		},
		{
			name:  "change is below the threshold",
			files: []*icsv.File{{Name: "AAPL", Rows: dailyRows(200, 202)}},
			cfg:   config.Check{ThresholdPct: 5},
			want:  nil,
		},
		{
			name:  "change equal to the threshold is not flagged",
			files: []*icsv.File{{Name: "AAPL", Rows: dailyRows(200, 250)}},
			cfg:   config.Check{ThresholdPct: 25},
			want:  nil,
		},
		{
			name:  "increase above the default threshold",
			files: []*icsv.File{{Name: "AAPL", Rows: dailyRows(200, 250)}},
			cfg:   config.Check{ThresholdPct: 5},
			want: []icsv.Result{{
				Ticker: "AAPL", Check: "day_over_day",
				PrevDate: day(2024, 1, 1), CurrDate: day(2024, 1, 2),
				PrevValue: 200, CurrValue: 250, AbsChange: 50, PctChange: 25,
				ThresholdPct: 5, ThresholdSource: "default", Direction: "up",
			}},
		},
		{
			name:  "decrease above the default threshold",
			files: []*icsv.File{{Name: "AAPL", Rows: dailyRows(200, 150)}},
			cfg:   config.Check{ThresholdPct: 5},
			want: []icsv.Result{{
				Ticker: "AAPL", Check: "day_over_day",
				PrevDate: day(2024, 1, 1), CurrDate: day(2024, 1, 2),
				PrevValue: 200, CurrValue: 150, AbsChange: -50, PctChange: -25,
				ThresholdPct: 5, ThresholdSource: "default", Direction: "down",
			}},
		},
		{
			name:  "higher override stops the flag",
			files: []*icsv.File{{Name: "AAPL", Rows: dailyRows(200, 250)}},
			cfg:   config.Check{ThresholdPct: 5, Overrides: map[string]float64{"AAPL": 30}},
			want:  nil,
		},
		{
			name:  "lower override causes a flag",
			files: []*icsv.File{{Name: "AAPL", Rows: dailyRows(200, 202)}},
			cfg:   config.Check{ThresholdPct: 5, Overrides: map[string]float64{"AAPL": 0.5}},
			want: []icsv.Result{{
				Ticker: "AAPL", Check: "day_over_day",
				PrevDate: day(2024, 1, 1), CurrDate: day(2024, 1, 2),
				PrevValue: 200, CurrValue: 202, AbsChange: 2, PctChange: 1,
				ThresholdPct: 0.5, ThresholdSource: "override", Direction: "up",
			}},
		},
		{
			name: "row that is not valid is not compared",
			files: []*icsv.File{{Name: "AAPL", Rows: []icsv.Row{
				valid(day(2024, 1, 1), 200),
				blank(day(2024, 1, 2)),
				valid(day(2024, 1, 3), 250),
			}}},
			cfg: config.Check{ThresholdPct: 5},
			want: []icsv.Result{{
				Ticker: "AAPL", Check: "day_over_day",
				PrevDate: day(2024, 1, 1), CurrDate: day(2024, 1, 3),
				PrevValue: 200, CurrValue: 250, AbsChange: 50, PctChange: 25,
				ThresholdPct: 5, ThresholdSource: "default", Direction: "up",
			}},
		},
		{
			name: "override applies only to its ticker",
			files: []*icsv.File{
				{Name: "AAPL", Rows: dailyRows(200, 250)},
				{Name: "MSFT", Rows: dailyRows(200, 250)},
			},
			cfg: config.Check{ThresholdPct: 5, Overrides: map[string]float64{"MSFT": 30}},
			want: []icsv.Result{{
				Ticker: "AAPL", Check: "day_over_day",
				PrevDate: day(2024, 1, 1), CurrDate: day(2024, 1, 2),
				PrevValue: 200, CurrValue: 250, AbsChange: 50, PctChange: 25,
				ThresholdPct: 5, ThresholdSource: "default", Direction: "up",
			}},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			r := &Runner{Data: &icsv.Store{Files: tt.files}}
			got := r.runChecker("day_over_day", tt.cfg, calendarBack(0, 0, 1))
			if diff := cmp.Diff(tt.want, got); diff != "" {
				t.Errorf("runChecker(%q, %+v) returned unexpected diff (-want +got):\n%s", "day_over_day", tt.cfg, diff)
			}
		})
	}
}

// TestNew makes sure that New stores its arguments in the Runner.
func TestNew(t *testing.T) {
	data := &icsv.Store{}
	rw := &icsv.ResultWriter{}
	cfg := config.Settings{Checks: config.Checks{DayOverDay: config.Check{Enabled: true, ThresholdPct: 5}}}

	r, err := New(data, rw, cfg)
	if err != nil {
		t.Fatalf("New() returned unexpected error: %v", err)
	}
	if r.Data != data {
		t.Errorf("New().Data = %p, want %p", r.Data, data)
	}
	if r.ResultWriter != rw {
		t.Errorf("New().ResultWriter = %p, want %p", r.ResultWriter, rw)
	}
	if diff := cmp.Diff(cfg, *r.Config); diff != "" {
		t.Errorf("New().Config returned unexpected diff (-want +got):\n%s", diff)
	}
}

// mustReadCSV reads all records from the CSV file at path. The test stops
// if the read fails.
func mustReadCSV(t *testing.T, path string) [][]string {
	t.Helper()
	f, err := os.Open(path)
	if err != nil {
		t.Fatalf("Setup failed: could not open %q: %v", path, err)
	}
	defer f.Close()
	records, err := csv.NewReader(f).ReadAll()
	if err != nil {
		t.Fatalf("Setup failed: could not parse %q: %v", path, err)
	}
	return records
}

// TestExecute runs the enabled checks from start to end and reads the
// results file back. The data has eight daily rows. The value doubles on
// the last day, so each enabled check flags that day one time.
func TestExecute(t *testing.T) {
	header := []string{
		"ticker", "check", "prev_date", "curr_date", "prev_value", "curr_value",
		"abs_change", "pct_change", "threshold_pct", "threshold_source", "direction",
	}
	dodRow := []string{"AAPL", "day_over_day", "2024-01-07", "2024-01-08", "100.00", "200.00", "100.00", "100.0000", "5.00", "default", "up"}
	wowRow := []string{"AAPL", "week_over_week", "2024-01-01", "2024-01-08", "100.00", "200.00", "100.00", "100.0000", "5.00", "default", "up"}

	tests := []struct {
		name   string
		checks config.Checks
		want   [][]string
	}{
		{
			name: "both checks enabled",
			checks: config.Checks{
				DayOverDay:   config.Check{Enabled: true, ThresholdPct: 5},
				WeekOverWeek: config.Check{Enabled: true, ThresholdPct: 5},
			},
			want: [][]string{header, dodRow, wowRow},
		},
		{
			name: "only day_over_day enabled",
			checks: config.Checks{
				DayOverDay:   config.Check{Enabled: true, ThresholdPct: 5},
				WeekOverWeek: config.Check{Enabled: false, ThresholdPct: 5},
			},
			want: [][]string{header, dodRow},
		},
		{
			name: "only week_over_week enabled",
			checks: config.Checks{
				DayOverDay:   config.Check{Enabled: false, ThresholdPct: 5},
				WeekOverWeek: config.Check{Enabled: true, ThresholdPct: 5},
			},
			want: [][]string{header, wowRow},
		},
		{
			name:   "no checks enabled",
			checks: config.Checks{},
			want:   [][]string{header},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := t.TempDir()
			rw, err := icsv.NewResultWriter(dir)
			if err != nil {
				t.Fatalf("Setup failed: NewResultWriter(%q) returned error: %v", dir, err)
			}
			t.Cleanup(func() { rw.Close() })

			data := &icsv.Store{Files: []*icsv.File{
				{Name: "AAPL", Rows: dailyRows(100, 100, 100, 100, 100, 100, 100, 200)},
			}}
			r, err := New(data, rw, config.Settings{Checks: tt.checks})
			if err != nil {
				t.Fatalf("Setup failed: New() returned error: %v", err)
			}

			if err := r.Execute(); err != nil {
				t.Errorf("Execute() returned unexpected error: %v", err)
			}
			if diff := cmp.Diff(tt.want, mustReadCSV(t, rw.Path)); diff != "" {
				t.Errorf("Execute() results file returned unexpected diff (-want +got):\n%s", diff)
			}
		})
	}
}

// TestExecute_writeError closes the results file before Execute runs, so
// each write fails. Execute must run all enabled checks and return one
// joined error that names each check.
func TestExecute_writeError(t *testing.T) {
	dir := t.TempDir()
	rw, err := icsv.NewResultWriter(dir)
	if err != nil {
		t.Fatalf("Setup failed: NewResultWriter(%q) returned error: %v", dir, err)
	}
	if err := rw.Close(); err != nil {
		t.Fatalf("Setup failed: Close() returned error: %v", err)
	}

	data := &icsv.Store{Files: []*icsv.File{
		{Name: "AAPL", Rows: dailyRows(100, 100, 100, 100, 100, 100, 100, 200)},
	}}
	cfg := config.Settings{Checks: config.Checks{
		DayOverDay:   config.Check{Enabled: true, ThresholdPct: 5},
		WeekOverWeek: config.Check{Enabled: true, ThresholdPct: 5},
	}}
	r, err := New(data, rw, cfg)
	if err != nil {
		t.Fatalf("Setup failed: New() returned error: %v", err)
	}

	err = r.Execute()
	if err == nil {
		t.Fatal("Execute() = nil, want error")
	}
	for _, want := range []string{"write day_over_day", "write week_over_week"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("Execute() = %q, want error that contains %q", err, want)
		}
	}
}
