// AI-assisted (Claude Code): this test file was generated by AI.

package csv

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/google/go-cmp/cmp"
)

// day returns midnight UTC on the given date.
func day(year int, month time.Month, d int) time.Time {
	return time.Date(year, month, d, 0, 0, 0, 0, time.UTC)
}

// mustWriteFile writes contents to path. The test stops if the write fails.
func mustWriteFile(t *testing.T, path, contents string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
		t.Fatalf("Setup failed: could not write %q: %v", path, err)
	}
}

// TestRead parses one CSV file. Each case gives the file contents and the
// File or the error that read must return. If wantErr is not empty, the
// error text must contain it.
func TestRead(t *testing.T) {
	tests := []struct {
		name     string
		contents string
		want     *File
		wantErr  string
	}{
		{
			name:     "rows are sorted by date",
			contents: "date,AAPL\n2024-01-03,12\n2024-01-01,10.5\n2024-01-02,11\n",
			want: &File{Name: "AAPL", Rows: []Row{
				{Date: day(2024, 1, 1), Value: 10.5, Valid: true},
				{Date: day(2024, 1, 2), Value: 11, Valid: true},
				{Date: day(2024, 1, 3), Value: 12, Valid: true},
			}},
		},
		{
			name:     "blank value gives a row that is not valid",
			contents: "date,MSFT\n2024-01-01,\n2024-01-02,20\n",
			want: &File{Name: "MSFT", Rows: []Row{
				{Date: day(2024, 1, 1)},
				{Date: day(2024, 1, 2), Value: 20, Valid: true},
			}},
		},
		{
			name:     "header only",
			contents: "date,AAPL\n",
			want:     &File{Name: "AAPL"},
		},
		{
			name:     "empty file",
			contents: "",
			wantErr:  "encountered empty csv file",
		},
		{
			name:     "header has one column",
			contents: "date\n",
			wantErr:  "parse header",
		},
		{
			name:     "row has three columns",
			contents: "date,AAPL\n2024-01-01,10,11\n",
			wantErr:  "wrong number of fields",
		},
		{
			name:     "date is not valid",
			contents: "date,AAPL\n2024-01-01,10\n01/02/2024,11\n",
			wantErr:  "data.csv:3: parse date",
		},
		{
			name:     "value is not a number",
			contents: "date,AAPL\n2024-01-01,abc\n",
			wantErr:  "data.csv:2: parse value",
		},
		{
			name:     "value is zero",
			contents: "date,AAPL\n2024-01-01,0\n",
			wantErr:  "data.csv:2: value must be > 0, got 0",
		},
		{
			name:     "value is negative",
			contents: "date,AAPL\n2024-01-01,-3\n",
			wantErr:  "data.csv:2: value must be > 0, got -3",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			path := filepath.Join(t.TempDir(), "data.csv")
			mustWriteFile(t, path, tt.contents)

			got, err := read(path)
			if tt.wantErr != "" {
				if err == nil || !strings.Contains(err.Error(), tt.wantErr) {
					t.Errorf("read(%q) error = %v, want error that contains %q", path, err, tt.wantErr)
				}
				return
			}
			if err != nil {
				t.Fatalf("read(%q) returned unexpected error: %v", path, err)
			}
			if diff := cmp.Diff(tt.want, got); diff != "" {
				t.Errorf("read(%q) returned unexpected diff (-want +got):\n%s", path, diff)
			}
		})
	}
}

// TestRead_missingFile makes sure that read returns an error when the file
// does not exist.
func TestRead_missingFile(t *testing.T) {
	path := filepath.Join(t.TempDir(), "missing.csv")
	if _, err := read(path); err == nil || !strings.Contains(err.Error(), "open") {
		t.Errorf("read(%q) error = %v, want error that contains %q", path, err, "open")
	}
}

// TestLoadDir loads all CSV files from one directory. Each case gives the
// files and the subdirectories to create. The test compares the ticker
// names of the loaded files, in load order.
func TestLoadDir(t *testing.T) {
	tests := []struct {
		name  string
		files map[string]string
		dirs  []string
		// noDir tells the test to pass a directory that does not exist.
		noDir       bool
		wantTickers []string
		wantErr     string
	}{
		{
			name: "loads files in file name order",
			files: map[string]string{
				"b.csv": "date,MSFT\n2024-01-01,20\n",
				"a.csv": "date,AAPL\n2024-01-01,10\n",
			},
			wantTickers: []string{"AAPL", "MSFT"},
		},
		{
			name: "file extension match ignores case",
			files: map[string]string{
				"a.CSV": "date,AAPL\n2024-01-01,10\n",
			},
			wantTickers: []string{"AAPL"},
		},
		{
			name: "skips other files and subdirectories",
			files: map[string]string{
				"a.csv":     "date,AAPL\n2024-01-01,10\n",
				"notes.txt": "not data",
			},
			dirs:        []string{"nested.csv"},
			wantTickers: []string{"AAPL"},
		},
		{
			name:        "empty directory",
			wantTickers: []string{},
		},
		{
			name: "one bad file stops the load",
			files: map[string]string{
				"a.csv": "date,AAPL\n2024-01-01,10\n",
				"b.csv": "",
			},
			wantErr: "encountered empty csv file",
		},
		{
			name:    "directory does not exist",
			noDir:   true,
			wantErr: "read dir",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := t.TempDir()
			for name, contents := range tt.files {
				mustWriteFile(t, filepath.Join(dir, name), contents)
			}
			for _, name := range tt.dirs {
				if err := os.Mkdir(filepath.Join(dir, name), 0o755); err != nil {
					t.Fatalf("Setup failed: could not create directory %q: %v", name, err)
				}
			}
			if tt.noDir {
				dir = filepath.Join(dir, "missing")
			}

			store, err := LoadDir(dir)
			if tt.wantErr != "" {
				if err == nil || !strings.Contains(err.Error(), tt.wantErr) {
					t.Errorf("LoadDir(%q) error = %v, want error that contains %q", dir, err, tt.wantErr)
				}
				return
			}
			if err != nil {
				t.Fatalf("LoadDir(%q) returned unexpected error: %v", dir, err)
			}
			if diff := cmp.Diff(tt.wantTickers, store.Tickers()); diff != "" {
				t.Errorf("LoadDir(%q) tickers returned unexpected diff (-want +got):\n%s", dir, diff)
			}
		})
	}
}

// TestTickers makes sure that Tickers returns the name of each file in the
// Store, in the same order as the files.
func TestTickers(t *testing.T) {
	tests := []struct {
		name  string
		store *Store
		want  []string
	}{
		{
			name:  "no files",
			store: &Store{},
			want:  []string{},
		},
		{
			name:  "keeps load order",
			store: &Store{Files: []*File{{Name: "MSFT"}, {Name: "AAPL"}}},
			want:  []string{"MSFT", "AAPL"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if diff := cmp.Diff(tt.want, tt.store.Tickers()); diff != "" {
				t.Errorf("Tickers() returned unexpected diff (-want +got):\n%s", diff)
			}
		})
	}
}
