// AI-assisted (Claude Code): this test file was generated by AI.

package csv

import (
	"encoding/csv"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
)

// resultFileName is the pattern for the name of a results file, for
// example 20261008T113631_result.csv.
var resultFileName = regexp.MustCompile(`^\d{8}T\d{6}_result\.csv$`)

// mustReadCSV reads all records from the CSV file at path. The test stops
// if the read fails.
func mustReadCSV(t *testing.T, path string) [][]string {
	t.Helper()
	f, err := os.Open(path)
	if err != nil {
		t.Fatalf("Setup failed: could not open %q: %v", path, err)
	}
	defer f.Close()
	records, err := csv.NewReader(f).ReadAll()
	if err != nil {
		t.Fatalf("Setup failed: could not parse %q: %v", path, err)
	}
	return records
}

// TestResultRecord makes sure that record formats each field of a Result
// in the column order of csvHeader. Prices use two decimal places and the
// percent change uses four.
func TestResultRecord(t *testing.T) {
	tests := []struct {
		name   string
		result Result
		want   []string
	}{
		{
			name: "increase",
			result: Result{
				Ticker:          "AAPL",
				Check:           "day_over_day",
				PrevDate:        day(2024, 1, 1),
				CurrDate:        day(2024, 1, 2),
				PrevValue:       100,
				CurrValue:       110.456,
				AbsChange:       10.456,
				PctChange:       10.456,
				ThresholdPct:    5,
				ThresholdSource: "default",
				Direction:       "up",
			},
			want: []string{
				"AAPL", "day_over_day", "2024-01-01", "2024-01-02", "100.00", "110.46",
				"10.46", "10.4560", "5.00", "default", "up",
			},
		},
		{
			name: "decrease",
			result: Result{
				Ticker:          "MSFT",
				Check:           "week_over_week",
				PrevDate:        day(2024, 1, 1),
				CurrDate:        day(2024, 1, 8),
				PrevValue:       200,
				CurrValue:       150,
				AbsChange:       -50,
				PctChange:       -25,
				ThresholdPct:    12.5,
				ThresholdSource: "override",
				Direction:       "down",
			},
			want: []string{
				"MSFT", "week_over_week", "2024-01-01", "2024-01-08", "200.00", "150.00",
				"-50.00", "-25.0000", "12.50", "override", "down",
			},
		},
		{
			name:   "zero value",
			result: Result{},
			want: []string{
				"", "", "0001-01-01", "0001-01-01", "0.00", "0.00",
				"0.00", "0.0000", "0.00", "", "",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if diff := cmp.Diff(tt.want, tt.result.record()); diff != "" {
				t.Errorf("Result.record() returned unexpected diff (-want +got):\n%s", diff)
			}
		})
	}
}

// TestResultWriter creates a results file, writes zero or more batches of
// results to it, and closes it. Then the test reads the file back. The file
// must contain the header and then one row for each result, in the order
// of the writes.
func TestResultWriter(t *testing.T) {
	aapl := Result{Ticker: "AAPL", Check: "day_over_day", PrevDate: day(2024, 1, 1), CurrDate: day(2024, 1, 2),
		PrevValue: 200, CurrValue: 250, AbsChange: 50, PctChange: 25, ThresholdPct: 5, ThresholdSource: "default", Direction: "up"}
	msft := Result{Ticker: "MSFT", Check: "week_over_week", PrevDate: day(2024, 1, 1), CurrDate: day(2024, 1, 8),
		PrevValue: 200, CurrValue: 150, AbsChange: -50, PctChange: -25, ThresholdPct: 10, ThresholdSource: "override", Direction: "down"}

	tests := []struct {
		name string
		// subdir is a path under the temporary directory. If it is not
		// empty, NewResultWriter must create it.
		subdir  string
		batches [][]Result
		want    [][]string
	}{
		{
			name: "no writes gives header only",
			want: [][]string{csvHeader},
		},
		{
			name:    "empty batch gives header only",
			batches: [][]Result{nil},
			want:    [][]string{csvHeader},
		},
		{
			name:    "one batch",
			batches: [][]Result{{aapl, msft}},
			want:    [][]string{csvHeader, aapl.record(), msft.record()},
		},
		{
			name:    "two batches are appended in order",
			batches: [][]Result{{msft}, {aapl}},
			want:    [][]string{csvHeader, msft.record(), aapl.record()},
		},
		{
			name:    "creates missing directories",
			subdir:  filepath.Join("out", "nested"),
			batches: [][]Result{{aapl}},
			want:    [][]string{csvHeader, aapl.record()},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := filepath.Join(t.TempDir(), tt.subdir)

			rw, err := NewResultWriter(dir)
			if err != nil {
				t.Fatalf("NewResultWriter(%q) returned unexpected error: %v", dir, err)
			}
			for _, batch := range tt.batches {
				if err := rw.Write(batch); err != nil {
					t.Errorf("Write(%v) returned unexpected error: %v", batch, err)
				}
			}
			if err := rw.Close(); err != nil {
				t.Errorf("Close() returned unexpected error: %v", err)
			}

			if got := filepath.Dir(rw.Path); got != dir {
				t.Errorf("NewResultWriter(%q).Path directory = %q, want %q", dir, got, dir)
			}
			if name := filepath.Base(rw.Path); !resultFileName.MatchString(name) {
				t.Errorf("NewResultWriter(%q).Path file name = %q, want match for %q", dir, name, resultFileName)
			}
			if diff := cmp.Diff(tt.want, mustReadCSV(t, rw.Path)); diff != "" {
				t.Errorf("file %q returned unexpected diff (-want +got):\n%s", rw.Path, diff)
			}
		})
	}
}

// TestNewResultWriter_errors gives NewResultWriter a directory that it
// cannot use. Each case prepares the directory and gives the text that the
// error must contain.
func TestNewResultWriter_errors(t *testing.T) {
	tests := []struct {
		name string
		// setup prepares the test state in base and returns the directory
		// to pass to NewResultWriter.
		setup   func(t *testing.T, base string) string
		wantErr string
	}{
		{
			name: "path is a file",
			setup: func(t *testing.T, base string) string {
				path := filepath.Join(base, "file")
				mustWriteFile(t, path, "")
				return path
			},
			wantErr: "create output dir",
		},
		{
			name: "parent of path is a file",
			setup: func(t *testing.T, base string) string {
				path := filepath.Join(base, "file")
				mustWriteFile(t, path, "")
				return filepath.Join(path, "out")
			},
			wantErr: "create output dir",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := tt.setup(t, t.TempDir())
			rw, err := NewResultWriter(dir)
			if err == nil {
				rw.Close()
				t.Fatalf("NewResultWriter(%q) = nil error, want error that contains %q", dir, tt.wantErr)
			}
			if !strings.Contains(err.Error(), tt.wantErr) {
				t.Errorf("NewResultWriter(%q) error = %v, want error that contains %q", dir, err, tt.wantErr)
			}
		})
	}
}

// TestResultWriter_writeAfterClose makes sure that Write returns an error
// when the file is already closed.
func TestResultWriter_writeAfterClose(t *testing.T) {
	dir := t.TempDir()
	rw, err := NewResultWriter(dir)
	if err != nil {
		t.Fatalf("NewResultWriter(%q) returned unexpected error: %v", dir, err)
	}
	if err := rw.Close(); err != nil {
		t.Fatalf("Close() returned unexpected error: %v", err)
	}

	results := []Result{{Ticker: "AAPL"}}
	if err := rw.Write(results); err == nil {
		t.Errorf("Write(%v) after Close() = nil, want error", results)
	}
}
