// AI-assisted (Claude Code): this test file was generated by AI.

package config

import (
	"math"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
)

// validYAML is a configuration file that sets every required key.
const validYAML = `
checks:
  day_over_day:
    enabled: true
    threshold_pct: 5
    overrides:
      AAPL: 10
  week_over_week:
    enabled: false
    threshold_pct: 8
`

// mustWriteConfig writes contents to a file in a temporary directory and
// returns the path of the file. The test stops if the write fails.
func mustWriteConfig(t *testing.T, contents string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "config.yaml")
	if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
		t.Fatalf("Setup failed: could not write %q: %v", path, err)
	}
	return path
}

// TestLoad reads configuration files from disk. Each case gives the file
// contents and the Settings or the error that Load must return. If wantErr
// is not empty, the error text must contain it.
func TestLoad(t *testing.T) {
	tests := []struct {
		name     string
		contents string
		// noFile tells the test to pass a path to a file that does not exist.
		noFile  bool
		want    *Settings
		wantErr string
	}{
		{
			name:     "valid file",
			contents: validYAML,
			want: &Settings{Checks: Checks{
				DayOverDay:   Check{Enabled: true, ThresholdPct: 5, Overrides: map[string]float64{"AAPL": 10}},
				WeekOverWeek: Check{Enabled: false, ThresholdPct: 8},
			}},
		},
		{
			name:    "file does not exist",
			noFile:  true,
			wantErr: "read config",
		},
		{
			name:     "empty file",
			contents: "",
			wantErr:  `missing required key "checks"`,
		},
		{
			name: "missing day_over_day",
			contents: `
checks:
  week_over_week:
    enabled: true
    threshold_pct: 8
`,
			wantErr: `missing required key "checks.day_over_day"`,
		},
		{
			name: "missing enabled",
			contents: `
checks:
  day_over_day:
    threshold_pct: 5
  week_over_week:
    enabled: true
    threshold_pct: 8
`,
			wantErr: `missing required key "checks.day_over_day.enabled"`,
		},
		{
			name: "missing threshold_pct",
			contents: `
checks:
  day_over_day:
    enabled: true
    threshold_pct: 5
  week_over_week:
    enabled: true
`,
			wantErr: `missing required key "checks.week_over_week.threshold_pct"`,
		},
		{
			name: "unknown key",
			contents: `
checks:
  day_over_day:
    enabled: true
    threshold_pct: 5
    treshold: 5
  week_over_week:
    enabled: true
    threshold_pct: 8
`,
			wantErr: "parse config",
		},
		{
			name: "duplicate key",
			contents: `
checks:
  day_over_day:
    enabled: true
    enabled: false
    threshold_pct: 5
  week_over_week:
    enabled: true
    threshold_pct: 8
`,
			wantErr: "parse config",
		},
		{
			name:     "not valid YAML",
			contents: "checks: [",
			wantErr:  "parse config",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			path := filepath.Join(t.TempDir(), "missing.yaml")
			if !tt.noFile {
				path = mustWriteConfig(t, tt.contents)
			}

			got, err := Load(path)
			if tt.wantErr != "" {
				if err == nil || !strings.Contains(err.Error(), tt.wantErr) {
					t.Errorf("Load(%q) error = %v, want error that contains %q", path, err, tt.wantErr)
				}
				return
			}
			if err != nil {
				t.Fatalf("Load(%q) returned unexpected error: %v", path, err)
			}
			if diff := cmp.Diff(tt.want, got); diff != "" {
				t.Errorf("Load(%q) returned unexpected diff (-want +got):\n%s", path, diff)
			}
		})
	}
}

// TestValidate gives Validate a Settings value and a list of tickers. A
// ticker is the name of one loaded data file. If wantErrs is empty,
// Validate must return nil. If not, the error text must contain each
// string in wantErrs.
func TestValidate(t *testing.T) {
	tickers := []string{"AAPL", "MSFT"}

	tests := []struct {
		name     string
		settings Settings
		wantErrs []string
	}{
		{
			name: "valid settings",
			settings: Settings{Checks: Checks{
				DayOverDay:   Check{ThresholdPct: 5, Overrides: map[string]float64{"AAPL": 10}},
				WeekOverWeek: Check{ThresholdPct: 8},
			}},
		},
		{
			name: "threshold is zero",
			settings: Settings{Checks: Checks{
				DayOverDay:   Check{ThresholdPct: 0},
				WeekOverWeek: Check{ThresholdPct: 8},
			}},
			wantErrs: []string{"checks.day_over_day.threshold_pct must be > 0, got 0"},
		},
		{
			name: "threshold is negative",
			settings: Settings{Checks: Checks{
				DayOverDay:   Check{ThresholdPct: 5},
				WeekOverWeek: Check{ThresholdPct: -1},
			}},
			wantErrs: []string{"checks.week_over_week.threshold_pct must be > 0, got -1"},
		},
		{
			name: "threshold is NaN",
			settings: Settings{Checks: Checks{
				DayOverDay:   Check{ThresholdPct: math.NaN()},
				WeekOverWeek: Check{ThresholdPct: 8},
			}},
			wantErrs: []string{"checks.day_over_day.threshold_pct must be > 0, got NaN"},
		},
		{
			name: "override is zero",
			settings: Settings{Checks: Checks{
				DayOverDay:   Check{ThresholdPct: 5, Overrides: map[string]float64{"MSFT": 0}},
				WeekOverWeek: Check{ThresholdPct: 8},
			}},
			wantErrs: []string{"checks.day_over_day.overrides.MSFT must be > 0, got 0"},
		},
		{
			name: "override ticker has wrong case",
			settings: Settings{Checks: Checks{
				DayOverDay:   Check{ThresholdPct: 5, Overrides: map[string]float64{"aapl": 10}},
				WeekOverWeek: Check{ThresholdPct: 8},
			}},
			wantErrs: []string{`checks.day_over_day.overrides: unknown ticker "aapl" (did you mean "AAPL"?)`},
		},
		{
			name: "override ticker is unknown",
			settings: Settings{Checks: Checks{
				DayOverDay:   Check{ThresholdPct: 5},
				WeekOverWeek: Check{ThresholdPct: 8, Overrides: map[string]float64{"TSLA": 10}},
			}},
			wantErrs: []string{`checks.week_over_week.overrides: unknown ticker "TSLA" (loaded: AAPL, MSFT)`},
		},
		{
			name: "all problems are reported together",
			settings: Settings{Checks: Checks{
				DayOverDay:   Check{ThresholdPct: 0, Overrides: map[string]float64{"TSLA": -2}},
				WeekOverWeek: Check{ThresholdPct: -1},
			}},
			wantErrs: []string{
				"checks.day_over_day.threshold_pct must be > 0, got 0",
				"checks.day_over_day.overrides.TSLA must be > 0, got -2",
				`checks.day_over_day.overrides: unknown ticker "TSLA"`,
				"checks.week_over_week.threshold_pct must be > 0, got -1",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.settings.Validate(tickers)
			if len(tt.wantErrs) == 0 {
				if err != nil {
					t.Errorf("Validate(%v) = %v, want nil", tickers, err)
				}
				return
			}
			if err == nil {
				t.Fatalf("Validate(%v) = nil, want error that contains %q", tickers, tt.wantErrs)
			}
			for _, want := range tt.wantErrs {
				if !strings.Contains(err.Error(), want) {
					t.Errorf("Validate(%v) = %q, want error that contains %q", tickers, err, want)
				}
			}
		})
	}
}
